### ISSUE TITLE
speed pyrabbit2 

### ISSUE THREAD

**Issue by folt** [deslum/pyrabbit2#11]
How fast can pyrabbit2 send messages to exchangers via http?

**Comment by deslum** [comment]
Pyrabbit2 and API Rabbitmq not supported send messages https://pulse.mozilla.org/api/

This is module for automation of administration

**Comment by deslum** [comment]
If you find such functionality, then I implement

**Comment by folt** [comment]
/api/exchanges/vhost/name/publish
Publish a message to a given exchange.

I want to test the stability of sending messages via http and amqp
But this library does not allow you to access the rabbitmq as an http

**Comment by deslum** [comment]
Ok. I will implement this feature.

Thank you for this issue

**Comment by deslum** [comment]
http://pyrabbit.readthedocs.io/en/latest/api.html

Method publish
