### ISSUE TITLE
Email advertising

### ISSUE THREAD

**Issue by Xorlev** [deslum/pyrabbit2#12]
I understand that you're very excited about your project, but emailing users from GitHub with an advertisement is not cool.

You (the.maintainers) should find a different means to promote your projects. I leave my email in my profile to help people with my own projects, but it's situations like this which unfortunately lead me to want to remove it.

**Comment by deslum** [comment]
sorry. This will not happen again

**Comment by superbobry** [comment]
I second @Xorlev here. I think cases like this should be reported to GitHub.

@deslum could you elaborate a bit on your motivation for doing this?

**Comment by deslum** [comment]
I did not indicate in the letter that you were interested in the rabbitmq project and it is possible that you will be interested in the project

I apologize again. This will not happen again.

**Comment by Xorlev** [comment]
I appreciate the good intentions and don't mean to discourage you by any means. I think you've created a very useful project. I intended this as just a heads up since email is a pretty touchy subject (especially without opt in and opt out links). 👍 Keep shippin' man, best of luck!
