### ISSUE TITLE
Difference from rabbitmq-admin

### ISSUE THREAD

**Issue by proofit404** [deslum/pyrabbit2#13]
Hi,

Thanks for working on this project! Can you point me to the main difference between your planned goal and rabbitmq-admin package?

https://pypi.python.org/pypi/rabbitmq-admin

Regards, Artem.

**Comment by deslum** [comment]
Support:

- Shovel
- User acess SHA256 + salt (Not Plain Text copy passwords between servers)

Expected:

- Federation
- Stomp

**Comment by proofit404** [comment]
Great! Thanks!
