### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by ckcollab** [deslum/pyrabbit2#15]
Hey there, are there any plans for adding SSL support to this? Similar to this PR in pyrabbit1:

https://github.com/bkjones/pyrabbit/pull/13

I don't mind doing the work if it will get merged, thanks!

**Comment by deslum** [comment]
Hi!
Now I do not use SSL If required, I implement. You can send Merge

Thanks for feedback

**Comment by deslum** [comment]
Https Support 

`pyrabbit2.api.Client(host_and_port, user, password, scheme='https') `

Use scheme='https'. For default scheme='http'

**Comment by ckcollab** [comment]
Awesome, thank you! I think I went with another python rabbitMQ library in the mean time but I appreciate the update
