### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hazmat345** [deslum/pyrabbit2#18]
Would you mind publishing a new version with the RabbitMQ 3.7 compatibility fix?

**Comment by deslum** [comment]
what is not compatible?

**Comment by deslum** [comment]
Support RabbitMQ version 3.7.4 
Test environment https://github.com/deslum/pyrabbit2/blob/master/.travis.yml
Tests https://travis-ci.org/deslum/pyrabbit2

**Comment by hazmat345** [comment]
That's correct, I think the work to make it compatible has already been done. But it looks like the latest version published on pypi is 1.0.0, and that version is from before the changes were added.

I don't think any more changes are needed, I'd just like for the current `master` branch to be published to pypi as a new version.

Sorry to bother you about this, it's just *much* easier for me to install things that are published to pypi.

**Comment by deslum** [comment]
all is well. I will do it

**Comment by deslum** [comment]
Done https://pypi.python.org/pypi/pyrabbit2

**Comment by hazmat345** [comment]
Awesome! Thank you!!

**Comment by hazmat345** [comment]
Not sure what happened, but trying to use the new version on Python 3 fails with a syntax error. Looks like an extra print statement was added to `http.py`:

```python
def __init__(self, api_url, uname, passwd, timeout=5, scheme='https'):
    """
    :param string api_url: The base URL for the broker API.
    :param string uname: Username credential used to authenticate.
    :param string passwd: Password used to authenticate w/ REST API
    :param int timeout: Integer number of seconds to wait for each call.
    :param string scheme: HTTP scheme used to connect

    """
    self.auth = HTTPBasicAuth(uname, passwd)
    self.timeout = timeout
    api_url = '%s://%s/api/' % (scheme, api_url)
    print api_url
    self.base_url = api_url
```

**Comment by deslum** [comment]
Sorry. Fixed

**Comment by hazmat345** [comment]
Thank you! 😄
