### ISSUE TITLE
Replacing pyrabbit with pyrabbit2 breaks code because do_call does not return data when JSON is "[]" or "{}"

### ISSUE THREAD

**Issue by rscrimojr** [deslum/pyrabbit2#21]
Thanks for maintaining and working on this library.  I have an issue.  In an attempt to replace pyrabbit with this library, I ran into the following problem.

This code breaks existing code and also returns an invalid value,` resp.status_code`, because of Python "falsey" evaluation of empty lists or dictionaries.  Because of "falsey" evaluation in Python, JSON of "[]" and "{}", converted to Python data structures with `resp.json()`, returns the `resp.status_code` when it should return the empty data, `content`, because there is actual data to return, it just happens to be empty.

To fix this I propose the following (in http.do_call(...)):

```
            if content is not None:
                return content
            else:
                return resp.status_code
```

Thank you for your consideration.  If you would like me to PR this solution,  please let me know.

Thanks,
Robert

**Comment by deslum** [comment]
Hi!
Thanks for contribute this issue. You can send pull request with the correction of the error or I can do it, but later

**Comment by rscrimojr** [comment]
Thanks for responding so quickly. Okay cool. I will PR the fix today.  

Thanks,
Robert

**Comment by rscrimojr** [comment]
@deslum Thank you for merging the change.  When do you think it will be published to PyPI?

**Comment by deslum** [comment]
Already done https://pypi.org/project/pyrabbit2/
